import "./globals.css";
import "node_modules/bootstrap/dist/css/bootstrap.min.css"; // Bootstrap css kalıtımıyla buradan tüm child componentlere iletiliyor

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="fixed-top"></header>
        <main className="min-vh-100">{children}</main>
        <footer
          className="text-center text-white"
          style={{ backgroundColor: "#3f51b5" }}
        ></footer>
      </body>
    </html>
  );
}
